[CISCO]
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: admin
ansible_password: admin
ansible_become: yes
ansible_become_method: enable
ansible_become_password: admin

NTP-SERVER:
  - 10.0.0.100
  - 10.0.0.101