---
- name: Using Ansible Vault
  hosts: all
  gather_facts: no
  vars_files:
    - secrets
  tasks:
    - name : Output OSPF password 
      debug:
        msg: "router {{ inventory_hostname }} OSPF password is {{ OSPF_password }}"
    - name : Output BGP password 
      debug:
        msg: "router {{ inventory_hostname }} BGP password is {{ BGP_password }}"
